name: smart_gantt_layout_view
description: "A smart gantt layout view that auto adjust the layout to handle overlapping."
version: 0.0.2
homepage: https://github.com/Code-Cats-Mel

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
